# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hogO0cYP_6mCXK5UMJ68NkcdoIRbuXaT

# **Task 4**
Analyze and visualize sentiment patterns in social media
data to understand public opinion and attitudes towards
specific topics or brands.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from textblob import TextBlob

# Sample social media posts
data = {
    'post': [
        "I love the new iPhone 15 Pro, it's amazing!",
        "The update completely ruined the app.",
        "Battery life is okay, not too bad.",
        "Service is excellent and fast delivery!",
        "The design feels outdated.",
        "Absolutely thrilled with the camera quality!",
        "Terrible customer support experience.",
        "Could be better, but it works.",
        "This product is worth every penny.",
        "Not satisfied with the performance."
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Sentiment Analysis using TextBlob
def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0.1:
        return 'Positive'
    elif polarity < -0.1:
        return 'Negative'
    else:
        return 'Neutral'

df['Sentiment'] = df['post'].apply(get_sentiment)

# View data
print(df)

# 📊 Bar plot of sentiment counts
plt.figure(figsize=(6,4))
sns.countplot(x='Sentiment', data=df, palette='Set2')
plt.title("Sentiment Distribution")
plt.ylabel("Number of Posts")
plt.show()

# ☁️ Word Cloud for all posts
all_text = " ".join(df['post'])
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud of Social Media Posts")
plt.show()